name: hungry_hound
description: A food ordering application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  get: ^4.6.5
  get_storage: ^2.1.1
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  loading_animation_widget: ^1.2.0+4
  image_picker: ^0.8.9
  uuid: ^3.0.7
  timer_count_down: ^2.2.2
  intl: ^0.18.1
  stop_watch_timer: ^2.0.0
  firebase_messaging: ^14.6.4
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rundeck
      fonts:
        - asset: assets/fonts/rundeck.ttf
